### ISSUE TITLE
Add types to web frontend

### ISSUE THREAD

**Issue by bwgoudey** [tool-bin/ukbcc#12]

**Comment by natwille1** [comment]
is this issue still relevant?

**Comment by bwgoudey** [comment]
I meant it in regards to the coding style of the webapp vs the rest of the
library. In particular, the webapp lacks typing info on the function
definitions. But it also lacks docstrings, tests etc which should be
addressed in separate issues I guess.

**Comment by natwille1** [comment]
okay great thanks Ben, we should definitely add docstrings and types before we merge to master and/or publish to pypi.. any chance you have time for this?

**Comment by natwille1** [comment]
done
