### ISSUE TITLE
Add button to file paths

### ISSUE THREAD

**Issue by bwgoudey** [tool-bin/ukbcc#14]
Not supported by plotly directly. Can hack something together either using plotly button + input or dash-bootstrap-components.

**Comment by natwille1** [comment]
not sure what this issue is about - could you clarify?

**Comment by bwgoudey** [comment]
In the settings, we need to define a path to the files. In many common
situations, you'd be able to type the path directly, or click a button to
open a file picker modal. I couldn't see any straight forward component to
use that combines these but there are some snippets of code out there
highlighting how such a component can be created in Dash IIRC

**Comment by natwille1** [comment]
okay lets close this for now
