### ISSUE TITLE
aux_dir is always relative to ./data_files?

### ISSUE THREAD

**Issue by bwgoudey** [tool-bin/ukbcc#21]
in the CLI version, it seems like aux_dir defaults to ./data_files and we give the user no option to change this?

**Comment by natwille1** [comment]
we dont have support for this atm - would be an easy fix but i think we do this for the next version?

**Comment by bwgoudey** [comment]
Can definitely wait until the next version

**Comment by natwille1** [comment]
removed this option from the UI front-end - I think it causes more confusion atm. I specified the default path as "./data_files", same as we do in the main.py
