### ISSUE TITLE
Kw_search_output bug

### ISSUE THREAD

**Issue by natwille1** [tool-bin/ukbcc#22]
[
<img width="608" alt="Screen Shot 2020-08-20 at 20 17 54" src="https://user-images.githubusercontent.com/36617813/90760666-96b59880-e325-11ea-96f6-46244465f6e9.png">
](url)

**Comment by natwille1** [comment]
i think this bug happens when a new session is launched and there's no cache?

**Comment by bwgoudey** [comment]
Fixed this error. We were detecting when this was only triggered by dash but were returning None rather than raising a PreventUPdate exception. This has been fixed.
