### ISSUE TITLE
saveconfig modal issue

### ISSUE THREAD

**Issue by natwille1** [tool-bin/ukbcc#23]
[
<img width="540" alt="Screen Shot 2020-08-20 at 21 03 06" src="https://user-images.githubusercontent.com/36617813/90762596-a387bb80-e328-11ea-89c9-dc113ae3ad47.png">
](url)

i think error occurs when new session is launched and no paths have been specified, and the output directory has not yet been created - how can we suppress this?

**Comment by bwgoudey** [comment]
This has been fixed by making sure that config only gets saved when we actually press the write config button.
